"""Italian geography and name/code mappings used by COVIDashFlow datasets."""

from collections import OrderedDict

ITALY_MAP = {
    "Abruzzo": ["Chieti", "L'Aquila", "Pescara", "Teramo"],
    "Basilicata": ["Matera", "Potenza"],
    "Calabria": [
        "Catanzaro",
        "Cosenza",
        "Crotone",
        "Reggio di Calabria",
        "Vibo Valentia",
    ],
    "Campania": ["Avellino", "Benevento", "Caserta", "Napoli", "Salerno"],
    "Emilia-Romagna": [
        "Bologna",
        "Ferrara",
        "Forlì-Cesena",
        "Modena",
        "Parma",
        "Piacenza",
        "Ravenna",
        "Reggio nell'Emilia",
        "Rimini",
    ],
    "Friuli Venezia Giulia": ["Gorizia", "Pordenone", "Trieste", "Udine"],
    "Lazio": ["Frosinone", "Latina", "Rieti", "Roma", "Viterbo"],
    "Liguria": ["Genova", "Imperia", "La Spezia", "Savona"],
    "Lombardia": [
        "Bergamo",
        "Brescia",
        "Como",
        "Cremona",
        "Lecco",
        "Lodi",
        "Mantova",
        "Milano",
        "Monza e della Brianza",
        "Pavia",
        "Sondrio",
        "Varese",
    ],
    "Marche": ["Ancona", "Ascoli Piceno", "Fermo", "Macerata", "Pesaro e Urbino"],
    "Molise": ["Campobasso", "Isernia"],
    "Piemonte": [
        "Alessandria",
        "Asti",
        "Biella",
        "Cuneo",
        "Novara",
        "Torino",
        "Verbano-Cusio-Ossola",
        "Vercelli",
    ],
    "Puglia": [
        "Bari",
        "Barletta-Andria-Trani",
        "Brindisi",
        "Lecce",
        "Foggia",
        "Taranto",
    ],
    "Sardegna": ["Cagliari", "Nuoro", "Sassari", "Sud Sardegna"],
    "Sicilia": [
        "Agrigento",
        "Caltanissetta",
        "Catania",
        "Enna",
        "Messina",
        "Palermo",
        "Ragusa",
        "Siracusa",
        "Trapani",
    ],
    "Toscana": [
        "Arezzo",
        "Firenze",
        "Grosseto",
        "Livorno",
        "Lucca",
        "Massa Carrara",
        "Pisa",
        "Pistoia",
        "Prato",
        "Siena",
    ],
    "P.A. Bolzano": [],
    "P.A. Trento": [],
    "Umbria": ["Perugia", "Terni"],
    "Valle d'Aosta": ["Aosta"],
    "Veneto": [
        "Belluno",
        "Padova",
        "Rovigo",
        "Treviso",
        "Venezia",
        "Verona",
        "Vicenza",
    ],
}

REGIONS = [region for region in ITALY_MAP]
PROVINCES = [province for provinces in ITALY_MAP.values() for province in provinces]

PC_TO_OD_MAP = {
    "Italia": "ITA",
    "Abruzzo": "ABR",
    "Basilicata": "BAS",
    "Calabria": "CAL",
    "Campania": "CAM",
    "Emilia-Romagna": "EMR",
    "Friuli Venezia Giulia": "FVG",
    "Lazio": "LAZ",
    "Liguria": "LIG",
    "Lombardia": "LOM",
    "Marche": "MAR",
    "Molise": "MOL",
    "P.A. Bolzano": "PAB",
    "P.A. Trento": "PAT",
    "Piemonte": "PIE",
    "Puglia": "PUG",
    "Sardegna": "SAR",
    "Sicilia": "SIC",
    "Toscana": "TOS",
    "Umbria": "UMB",
    "Valle d'Aosta": "VDA",
    "Veneto": "VEN",
}
OD_TO_PC_MAP = {value: key for key, value in PC_TO_OD_MAP.items()}

KEY_PERIODS = OrderedDict()
