import os

MONGO_URI = os.environ["MONGO_URI"]
NATIONAL_DATA_COLLECTION = os.environ["NATIONAL_DATA_COLLECTION"]
NATIONAL_TRENDS_COLLECTION = os.environ["NATIONAL_TRENDS_COLLECTION"]
NATIONAL_SERIES_COLLECTION = os.environ["NATIONAL_SERIES_COLLECTION"]
REGIONAL_DATA_COLLECTION = os.environ["REGIONAL_DATA_COLLECTION"]
REGIONAL_TRENDS_COLLECTION = os.environ["REGIONAL_TRENDS_COLLECTION"]
REGIONAL_SERIES_COLLECTION = os.environ["REGIONAL_SERIES_COLLECTION"]
REGIONAL_BREAKDOWN_COLLECTION = os.environ["REGIONAL_BREAKDOWN_COLLECTION"]
PROVINCIAL_DATA_COLLECTION = os.environ["PROVINCIAL_DATA_COLLECTION"]
PROVINCIAL_TRENDS_COLLECTION = os.environ["PROVINCIAL_TRENDS_COLLECTION"]
PROVINCIAL_SERIES_COLLECTION = os.environ["PROVINCIAL_SERIES_COLLECTION"]
PROVINCIAL_BREAKDOWN_COLLECTION = os.environ["PROVINCIAL_BREAKDOWN_COLLECTION"]
