version: '3'
services:
  mongo:
    image: mongo

  redis:
    image: redis

  app:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    links:
      - redis

  worker:
    build:
      context: "."
    command: celery -A celery_worker.celery worker --concurrency 4
    depends_on:
      - redis

  beat:
    build:
      context: "."
    command: celery -A celery_worker.celery beat
    depends_on:
      - redis
