FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
WORKDIR /app/etl
COPY etl/pyproject.toml ./
COPY etl/src ./src
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir .
CMD ["python", "-m", "covidashflow", "all", "--mode", "delta"]
