# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - covidash

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://covidashcr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_baaf8ecad515459ca5879e2c2fa4db9b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f8755a4c95514f949980afaf3bb17f65 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_baaf8ecad515459ca5879e2c2fa4db9b }}/covidash:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'covidash'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_14d21001a44e402da4a3258bbb770505 }}
        images: 'covidashcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_baaf8ecad515459ca5879e2c2fa4db9b }}/covidash:${{ github.sha }}'